INSERT INTO Question (id,question_text) VALUES ( 1,'When was .NET first released?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (1, '2000' , 0, 1 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (2, '2001' , 0, 1 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (3, '2002' , 1, 1 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (4, '2003' , 0, 1 );
INSERT INTO Question (id,question_text) VALUES ( 2,'What fictional company did Nancy Davolio work for?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (5, 'Contoso Ltd.' , 0, 2 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (6, 'Initech' , 0, 2 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (7, 'Fabrikam, Inc.' , 0, 2 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (8, 'Northwind Traders' , 1, 2 );
INSERT INTO Question (id,question_text) VALUES ( 3,'The first and still the oldest domain name on the internet is:' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (9, 'Network.com' , 0, 3 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (10, 'Alpha4.com' , 0, 3 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (11, 'Symbolics.com' , 1, 3 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (12, 'InterConnect.com' , 0, 3 );
INSERT INTO Question (id,question_text) VALUES ( 4,'Which is not actually a Thing.js?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (13, 'Mustache.js' , 0, 4 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (14, 'Hammer.js' , 0, 4 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (15, 'Horseradish.js' , 1, 4 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (16, 'Uglify.js' , 0, 4 );
INSERT INTO Question (id,question_text) VALUES ( 5,'In what year was the first Voice Over IP (VOIP) call made?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (17, '1973' , 1, 5 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (18, '1982' , 0, 5 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (19, '1991' , 0, 5 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (20, '1994' , 0, 5 );
INSERT INTO Question (id,question_text) VALUES ( 6,'"Chicago" was codename for what Microsoft product?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (21, 'Visual Basic' , 0, 6 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (22, 'Microsoft Surface' , 0, 6 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (23, 'Windows 95' , 1, 6 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (24, 'Xbox' , 0, 6 );
INSERT INTO Question (id,question_text) VALUES ( 7,'How many loop constructs are there in C#?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (25, '2' , 0, 7 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (26, '3' , 0, 7 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (27, '4' , 1, 7 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (28, '5' , 0, 7 );
INSERT INTO Question (id,question_text) VALUES ( 8,'What was the first CodePlex.com project?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (29, 'EntLib' , 0, 8 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (30, 'IronPython' , 1, 8 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (31, 'Ajax Toolkit' , 0, 8 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (32, 'JSON.Net' , 0, 8 );
INSERT INTO Question (id,question_text) VALUES ( 9,'Last name of the employee who wears Microsoft badge 00001' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (33, 'McDonald' , 1, 9 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (34, 'Gates' , 0, 9 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (35, 'Ballmer' , 0, 9 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (36, 'Allen' , 0, 9 );
INSERT INTO Question (id,question_text) VALUES ( 10,'When did Scott Hanselman join Microsoft?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (37, '2007' , 1, 10 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (38, '2000' , 0, 10 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (39, '2005' , 0, 10 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (40, '2009' , 0, 10 );
INSERT INTO Question (id,question_text) VALUES ( 11,'How big is a nibble?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (41, '4 bits' , 1, 11 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (42, '8 bits' , 0, 11 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (43, '16 bits' , 0, 11 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (44, '2 bits' , 0, 11 );
INSERT INTO Question (id,question_text) VALUES ( 12,'How many function calls did Windows 1.0 approximately have?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (45, '100' , 0, 12 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (46, '200' , 0, 12 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (47, '600' , 0, 12 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (48, '400' , 1, 12 );
INSERT INTO Question (id,question_text) VALUES ( 13,'Which Star Wars movie was filmed entirely in the studio?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (49, '1' , 0, 13 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (50, '2' , 0, 13 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (51, '3' , 1, 13 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (52, '4' , 0, 13 );
INSERT INTO Question (id,question_text) VALUES ( 14,'What is Superman''s Kryptonian name?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (53, 'Jor-El' , 0, 14 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (54, 'Zod' , 0, 14 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (55, 'Kal-El' , 1, 14 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (56, 'Jax-Ur' , 0, 14 );
INSERT INTO Question (id,question_text) VALUES ( 15,'What is the image name for the Windows Task Manager application?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (57, 'taskmgr' , 1, 15 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (58, 'tmanager' , 0, 15 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (59, 'wtaskmgr' , 0, 15 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (60, 'wintaskm' , 0, 15 );
INSERT INTO Question (id,question_text) VALUES ( 16,'When was the internet opened to commercial use?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (61, '1989' , 0, 16 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (62, '1992' , 0, 16 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (63, '1990' , 0, 16 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (64, '1991' , 1, 16 );
INSERT INTO Question (id,question_text) VALUES ( 17,'When was the Xbox unveiled?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (65, '2000' , 0, 17 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (66, '2001' , 1, 17 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (67, '2002' , 0, 17 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (68, '2003' , 0, 17 );
INSERT INTO Question (id,question_text) VALUES ( 18,'What is the value of an Object + Array in JavaScript?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (69, '0' , 1, 18 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (70, 'Array' , 0, 18 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (71, 'Object' , 0, 18 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (72, 'Type Error' , 0, 18 );
INSERT INTO Question (id,question_text) VALUES ( 19,'Why was the IBM PCjr despised by users?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (73, 'Chicklet keyboard' , 0, 19 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (74, 'No Hard Disk' , 0, 19 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (75, 'Not PC compatible' , 0, 19 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (76, 'All the above' , 1, 19 );
INSERT INTO Question (id,question_text) VALUES ( 20,'What was the max memory supported by MS-DOS?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (77, '256K' , 0, 20 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (78, '512K' , 0, 20 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (79, '640K' , 0, 20 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (80, '1M' , 1, 20 );
INSERT INTO Question (id,question_text) VALUES ( 21,'When was the first laser mouse released?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (81, '2001' , 0, 21 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (82, '2002' , 0, 21 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (83, '2003' , 0, 21 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (84, '2004' , 1, 21 );
INSERT INTO Question (id,question_text) VALUES ( 22,'What was Microsoft''s first product?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (85, 'DOS' , 0, 22 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (86, 'Altair Basic' , 1, 22 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (87, 'PC Basic' , 0, 22 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (88, 'Windows' , 0, 22 );
INSERT INTO Question (id,question_text) VALUES ( 23,'What building does not exist on the Microsoft campus?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (89, '1' , 0, 23 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (90, '7' , 1, 23 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (91, '99' , 0, 23 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (92, '115' , 0, 23 );
INSERT INTO Question (id,question_text) VALUES ( 24,'Who wrote the first computer program?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (93, 'Charles Babbage' , 0, 24 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (94, 'Herman Hollerith' , 0, 24 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (95, 'Ada Lovelace' , 1, 24 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (96, 'Jakob Bernoulli' , 0, 24 );
INSERT INTO Question (id,question_text) VALUES ( 25,'Visual Basic was first released in what year?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (97, '1990' , 0, 25 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (98, '1991' , 1, 25 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (99, '1992' , 0, 25 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (100, '1993' , 0, 25 );
INSERT INTO Question (id,question_text) VALUES ( 26,'Which of the following is NOT a prime number?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (101, '257' , 0, 26 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (102, '379' , 0, 26 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (103, '571' , 0, 26 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (104, '697' , 1, 26 );
INSERT INTO Question (id,question_text) VALUES ( 27,'Yukihiro Matsumoto conceived what programming language on February 24, 1993?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (105, 'Python' , 0, 27 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (106, 'Ruby' , 1, 27 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (107, 'Perl' , 0, 27 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (108, 'Boo' , 0, 27 );
INSERT INTO Question (id,question_text) VALUES ( 28,'Which release of the .NET Framework introduced support for dynamic languages?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (109, '1.1' , 0, 28 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (110, '2.0' , 0, 28 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (111, '3.5' , 0, 28 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (112, '4.0' , 1, 28 );
INSERT INTO Question (id,question_text) VALUES ( 29,'What is the package manager for Node.js?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (113, 'npm' , 1, 29 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (114, 'yum' , 0, 29 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (115, 'rpm' , 0, 29 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (116, 'PEAR' , 0, 29 );
INSERT INTO Question (id,question_text) VALUES ( 30,'In the acronym PaaS, what do the P stand for' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (117, 'Programming' , 0, 30 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (118, 'Power' , 0, 30 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (119, 'Platform' , 1, 30 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (120, 'Pedestrian' , 0, 30 );
INSERT INTO Question (id,question_text) VALUES ( 31,'What is the speed of light in metres per second?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (121, '299,792,458' , 1, 31 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (122, '312,123,156' , 0, 31 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (123, '100,000,000' , 0, 31 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (124, '541,123,102' , 0, 31 );
INSERT INTO Question (id,question_text) VALUES ( 32,'What was the original name of the C# programming language?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (125, 'Boo' , 0, 32 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (126, 'C+++' , 0, 32 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (127, 'Cool' , 1, 32 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (128, 'Anders' , 0, 32 );
INSERT INTO Question (id,question_text) VALUES ( 33,'Which of the following is an example of Boxing in C#?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (129, 'int foo = 12;' , 0, 33 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (130, 'System.Box(56);' , 0, 33 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (131, 'int foo = (int)bar;' , 0, 33 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (132, 'object bar = 42;' , 1, 33 );
INSERT INTO Question (id,question_text) VALUES ( 34,'Which of the following was not an alternative name considered for XML?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (133, 'MAGMA' , 0, 34 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (134, 'SGML' , 1, 34 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (135, 'SLIM' , 0, 34 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (136, 'MGML' , 0, 34 );
INSERT INTO Question (id,question_text) VALUES ( 35,'How many HTML tags are defined in the original description of the markup language?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (137, '1' , 0, 35 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (138, '11' , 0, 35 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (139, '18' , 1, 35 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (140, '25' , 0, 35 );
INSERT INTO Question (id,question_text) VALUES ( 36,'Which of the following ECMA standards represents the standardization of JavaScript?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (141, 'ECMA-123' , 0, 36 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (142, 'ECMA-262' , 1, 36 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (143, 'ECMA-301' , 0, 36 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (144, 'ECMA-431' , 0, 36 );
INSERT INTO Question (id,question_text) VALUES ( 37,'What was the first Web Browser called?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (145, 'WorldWideWeb' , 1, 37 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (146, 'Mosaic' , 0, 37 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (147, 'Lynx' , 0, 37 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (148, 'Gopher' , 0, 37 );
INSERT INTO Question (id,question_text) VALUES ( 38,'In version control systems, the process of bringing together two sets of changes is called what?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (149, 'Branch' , 0, 38 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (150, 'Commit' , 0, 38 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (151, 'Merge' , 1, 38 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (152, 'Share' , 0, 38 );
INSERT INTO Question (id,question_text) VALUES ( 39,'In 1980, Microsoft released there first operating system. What was it called?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (153, 'MS-DOS' , 0, 39 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (154, 'Windows' , 0, 39 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (155, 'Xenix' , 1, 39 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (156, 'Altair OS' , 0, 39 );
INSERT INTO Question (id,question_text) VALUES ( 40,'Which ASCII code (in decimal) represents the character B?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (157, '22' , 0, 40 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (158, '66' , 1, 40 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (159, '97' , 0, 40 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (160, '112' , 0, 40 );
INSERT INTO Question (id,question_text) VALUES ( 41,'Which are the first 6 decimal digits of Pi?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (161, '3.14159' , 1, 41 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (162, '3.14195' , 0, 41 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (163, '3.14132' , 0, 41 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (164, '3.14123' , 0, 41 );
INSERT INTO Question (id,question_text) VALUES ( 42,'Internet Protocol v4 provides approximately how many addresses?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (165, '1.5 billion' , 0, 42 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (166, '4.3 billion' , 1, 42 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (167, '55 billion' , 0, 42 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (168, '3.4 trillion' , 0, 42 );
INSERT INTO Question (id,question_text) VALUES ( 43,'What is Layer 4 of the OSI Model?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (169, 'Network Layer' , 0, 43 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (170, 'Transport Layer' , 1, 43 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (171, 'Session Layer' , 0, 43 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (172, 'Presentation Layer' , 0, 43 );
INSERT INTO Question (id,question_text) VALUES ( 44,'Which of the following is NOT a value type in the .NET Framework Common Type System?' );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (173, 'System.Integer' , 0, 44 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (174, 'System.String' , 1, 44 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (175, 'System.DateTime' , 0, 44 );
INSERT INTO AnswerOption (id,answer_text,is_true,question_id) VALUES (176, 'System.Float' , 0, 44 );
